# Run with: streamlit run dashboard.py
import streamlit as st
import pandas as pd
import os
from datetime import datetime
import glob
import matplotlib.pyplot as plt

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
import requests


# =========================
# Config & Constants
# =========================
LOG_DIR = "focus_logs"
BACKEND_UPLOAD_URL = "http://localhost:6000/api/reports/upload"

st.set_page_config(
    page_title="Study Focus Dashboard",
    page_icon="https://cdn-icons-png.flaticon.com/128/10397/10397171.png",
    layout="wide"
)

# =========================
# Global Styles (Glass + Dark)
# =========================
st.markdown("""
    <style>
        .main { background: linear-gradient(145deg, #0F2027, #203A43, #2C5364); }
        h1, h2, h3, h4 { color: #00F5D4 !important; }
        .stMetric, .stDataFrame, .stPyplot {
            background: rgba(255,255,255,0.07) !important;
            backdrop-filter: blur(16px) !important;
            border-radius: 18px !important;
            padding: 20px !important;
            border: 1px solid rgba(255,255,255,0.28) !important;
        }
        .stButton>button {
            background: linear-gradient(90deg, #00F5D4, #00FFA3) !important;
            color: black !important; font-weight: 650 !important;
            border-radius: 10px !important; padding: 8px 16px !important; border: none !important;
        }
    </style>
""", unsafe_allow_html=True)

# =========================
# Header with Logo
# =========================
from PIL import Image

try:
    logo = Image.open("analysis.png")  # your local logo file
except:
    logo = None

h1, h2 = st.columns([1, 12])
with h1:
    if logo is not None:
        st.image(logo, width=96)
with h2:
    st.title("YOUR REPORT")

st.write("This dashboard displays insights based on the CSV files generated by the live Study Buddy.")

# =========================
# Helpers
# =========================


# def upload_pdf_to_backend(pdf_path, title="Study Focus Report"):
#     try:
#         with open(pdf_path, "rb") as f:
#             files = {
#                 "pdf": ("report.pdf", f, "application/pdf")
#             }
#             data = {
#                 "title": title
#             }

#             # ⚠️ yaha token hardcode nahi kar rahe
#             # frontend analytics page secure rahega
#             res = requests.post(
#                BACKEND_UPLOAD_URL,

#                 files=files,
#                 data=data
#             )

#         return res.status_code == 200

#     except Exception as e:
#         st.error(f"Backend upload failed: {e}")
#         return False


def create_status_chart(df):
    fig, ax = plt.subplots(figsize=(8, 4))
    status_counts = df["status"].value_counts()
    ax.bar(status_counts.index, status_counts.values, color="#05917C")
    ax.set_title("Status Breakdown")
    plt.xticks(rotation=45)
    return fig

def create_focus_chart(df):
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(df["timestamp"], df["focus_score"], color="#00FF99")
    ax.set_title("Focus Score Trend")
    return fig


def upload_pdf_to_backend(pdf_path, title="Study Focus Report"):
    try:
        with open(pdf_path, "rb") as f:
            files = {
                "pdf": ("report.pdf", f, "application/pdf")
            }
            data = {
                "title": title
            }

            res = requests.post(
                BACKEND_UPLOAD_URL,
                files=files,
                data=data
            )

        return res.status_code == 200

    except Exception as e:
        st.error(f"Backend upload failed: {e}")
        return False





def available_dates():
    if not os.path.exists(LOG_DIR):
        return []
    files = sorted(glob.glob(os.path.join(LOG_DIR, "*.csv")))
    dates = [os.path.splitext(os.path.basename(f))[0] for f in files]
    return dates

def generate_weekly_report():
    history = []
    for file in glob.glob(os.path.join(LOG_DIR, "*.csv")):
        dfh = pd.read_csv(file)
        date_str = os.path.basename(file).replace(".csv", "")
        total = len(dfh)
        focused = dfh["status"].str.startswith("Focused").sum()
        focus_pct = (focused / total * 100) if total else 0
        avg_score = dfh["focus_score"].mean() if total else 0
        phone_events = dfh["phone_detected"].sum()
        history.append([date_str, round(focus_pct, 2), round(avg_score, 2), int(phone_events)])

    if not history:
        return None

    week_df = pd.DataFrame(history, columns=["Date", "Focus %", "Avg Score", "Phone Events"])
    week_df = week_df.sort_values("Date")

    pdf_path = "Weekly_Study_Report.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, 800, "📅 Weekly Study Focus Report")
    c.setFont("Helvetica", 12)
    c.drawString(50, 770, "Date        Focus%       AvgScore       PhoneDetections")
    y = 750
    for _, row in week_df.iterrows():
        c.drawString(50, y, f"{row['Date']}     {row['Focus %']}%           {row['Avg Score']}               {row['Phone Events']}")
        y -= 20
    c.save()
    return pdf_path

def generate_monthly_report():
    history = []
    for file in glob.glob(os.path.join(LOG_DIR, "*.csv")):
        dfh = pd.read_csv(file)
        date_str = os.path.basename(file).replace(".csv", "")
        try:
            file_date = datetime.strptime(date_str, "%Y-%m-%d")
        except:
            continue
        if file_date.month != datetime.now().month or file_date.year != datetime.now().year:
            continue

        total = len(dfh)
        focused = dfh["status"].str.startswith("Focused").sum()
        focus_pct = (focused / total * 100) if total else 0
        avg_score = dfh["focus_score"].mean() if total else 0
        phone_events = dfh["phone_detected"].sum()
        history.append([date_str, round(focus_pct, 2), round(avg_score, 2), int(phone_events)])

    if not history:
        return None

    month_df = pd.DataFrame(history, columns=["Date", "Focus %", "Avg Score", "Phone Events"])
    month_df = month_df.sort_values("Date")

    pdf_path = "Monthly_Study_Report.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, 800, "📅 Monthly Study Focus Report")
    c.setFont("Helvetica", 12)
    c.drawString(50, 770, "Date        Focus%       AvgScore       PhoneDetections")
    y = 750
    for _, row in month_df.iterrows():
        c.drawString(50, y, f"{row['Date']}     {row['Focus %']}%           {row['Avg Score']}               {row['Phone Events']}")
        y -= 20
    c.save()
    return pdf_path

# =========================
# Load Data (Date selector in sidebar)
# =========================
st.sidebar.header("Filters")
dates = available_dates()
if not dates:
    st.warning("No CSV file exists. First run `study_monitor.py`")
    st.stop()

selected_date = st.sidebar.selectbox("Select Date", dates, index=len(dates)-1)
csv_path = os.path.join(LOG_DIR, selected_date + ".csv")
df = pd.read_csv(csv_path)

# Parse & sort
df["timestamp"] = pd.to_datetime(df["timestamp"], errors='coerce')
df = df.dropna(subset=["timestamp"]).sort_values("timestamp")

# KPIs common
total_rows = len(df)
focused_rows = df["status"].str.startswith("Focused").sum()
focus_pct = (focused_rows / total_rows * 100) if total_rows else 0
avg_score = df["focus_score"].mean() if total_rows else 0

# =========================
# NAVBAR (Tabs)
# =========================
tabs = st.tabs([
    "Overview",
    "📈 Distraction Breakdown",
    "📱 Phone Detection Timeline",
    "📅 Export Reports",
    "🔄Comparison",
    "📊 History Trend",
    "🗂️ Raw Log"
])

# -------------------------
# 1) Overview
# -------------------------
with tabs[0]:
    k1, k2, k3 = st.columns(3)
    k1.metric("Total Records", f"{total_rows}")
    k2.metric("Time Focused (%)", f"{focus_pct:.1f}%")
    k3.metric("Average Focus Score", f"{avg_score:.1f}")

    st.subheader("Status Breakdown (Table)")
    status_counts = df["status"].value_counts().reset_index()
    status_counts.columns = ["status", "count"]
    st.dataframe(status_counts, use_container_width=True)

    st.subheader("Status Breakdown (Chart)")
    fig1, ax = plt.subplots(figsize=(18, 6))
    ax.bar(status_counts["status"], status_counts["count"], color="#05917C")
    ax.set_facecolor("#111111")
    fig1.patch.set_facecolor("#111111")
    ax.set_xlabel("Status", color="white")
    ax.set_ylabel("Count", color="white")
    ax.set_title("Status Breakdown Chart", color="white")
    ax.tick_params(axis="x", colors="white", rotation=45)
    ax.tick_params(axis="y", colors="white")
    st.pyplot(fig1)

    st.subheader("Focus Score Over Time")
    fig2, ax = plt.subplots(figsize=(15, 4))
    ax.set_facecolor("#111111")
    fig2.patch.set_facecolor("#111111")
    ax.plot(df["timestamp"], df["focus_score"], linewidth=2, color="#00FF99")
    ax.set_xlabel("Time", color="white")
    ax.set_ylabel("Focus Score", color="white")
    ax.set_title("Focus Score Trend", color="white")
    ax.tick_params(axis="x", colors="white", rotation=45)
    ax.tick_params(axis="y", colors="white")
    st.pyplot(fig2)

# -------------------------
# 2) Distraction Breakdown (Pie, dark)
# -------------------------
with tabs[1]:
    st.subheader("📈 Distraction Breakdown")
    pie_data = df["status"].value_counts()
    fig_pie, ax = plt.subplots(figsize=(4, 4))
    ax.set_facecolor("#000000")
    fig_pie.patch.set_facecolor("#000000")
    colors = ["#06BC7F", "#FFB347", "#8A2BE2", "#FF6B6B"]
    ax.pie(
        pie_data,
        labels=pie_data.index,
        autopct="%1.1f%%",
        startangle=120,
        colors=colors,
        textprops={'color': "white", 'fontsize': 11}
    )
    st.pyplot(fig_pie)

    

# -------------------------
# 3) Phone Detection Timeline
# -------------------------
with tabs[2]:
    st.subheader("📱 Phone Detection Timeline")
    phone_df = df[df["phone_detected"] == 1]
    if phone_df.empty:
        st.info("No phone events logged.")
    else:
        st.dataframe(phone_df[["timestamp", "status", "focus_score"]], use_container_width=True)

# -------------------------
# 4) Export Reports (Weekly / Monthly / Today)
# -------------------------
with tabs[3]:
    st.subheader("📅 Export Reports")
    col1, col2, col3 = st.columns(3)

    with col1:
        if st.button("🗂️ Weekly PDF"):
            pdf_file = generate_weekly_report()
            if pdf_file:
                with open(pdf_file, "rb") as f:
                    st.download_button(
                        label="⬇️ Download Weekly",
                        data=f,
                        file_name="Weekly_Study_Report.pdf",
                        mime="application/pdf"
                    )
            else:
                st.warning("No weekly data found.")

    with col2:
        if st.button("🗓️ Monthly PDF"):
            pdf_file = generate_monthly_report()
            if pdf_file:
                with open(pdf_file, "rb") as f:
                    st.download_button(
                        label="⬇️ Download Monthly",
                        data=f,
                        file_name="Monthly_Study_Report.pdf",
                        mime="application/pdf"
                    )
            else:
                st.warning("No data for this month.")

    # with col3:
    #     if st.button("📄 Today PDF"):
    #         pdf_path = "dashboard_report.pdf"
    #         c = canvas.Canvas(pdf_path, pagesize=A4)
    #         c.setFont("Helvetica-Bold", 18)
    #         c.drawString(50, 800, "Study Focus Dashboard Report")
    #         c.setFont("Helvetica", 12)
    #         c.drawString(50, 770, f"Total Records: {total_rows}")
    #         c.drawString(50, 750, f"Time Focused (%): {focus_pct:.1f}%")
    #         c.drawString(50, 730, f"Average Focus Score: {avg_score:.1f}")

    #         status_chart_path = "status_chart.png"
    #         fig1.savefig(status_chart_path, dpi=200, facecolor="#111111")
    #         c.drawImage(status_chart_path, 50, 450, width=500, height=250)

    #         focus_chart_path = "focus_chart.png"
    #         fig2.savefig(focus_chart_path, dpi=200, facecolor="#111111")
    #         c.drawImage(focus_chart_path, 50, 150, width=500, height=250)

    #         c.save()

    #         with open(pdf_path, "rb") as f:
    #             st.download_button(
    #                 label="⬇️ Download Today",
    #                 data=f,
    #                 file_name="Today_Study_Report.pdf",
    #                 mime="application/pdf"
    #             )
    with col3:
     if st.button("📄 Today PDF"):
        pdf_path = "dashboard_report.pdf"
        c = canvas.Canvas(pdf_path, pagesize=A4)

        # ---------- TEXT ----------
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, 820, "Study Focus Dashboard Report")

        c.setFont("Helvetica", 12)
        c.drawString(50, 790, f"Date: {selected_date}")
        c.drawString(50, 770, f"Time Focused: {focus_pct:.1f}%")
        c.drawString(50, 750, f"Average Focus Score: {avg_score:.1f}")

        # ---------- STATUS CHART (NEW FIG) ----------
        status_chart_path = "status_chart.png"
        fig_status, ax1 = plt.subplots(figsize=(6, 3))
        status_counts = df["status"].value_counts()
        ax1.bar(status_counts.index, status_counts.values, color="#05917C")
        ax1.set_title("Status Breakdown")
        plt.xticks(rotation=45)
        fig_status.savefig(status_chart_path, dpi=200, bbox_inches="tight")
        plt.close(fig_status)

        # ---------- FOCUS CHART (NEW FIG) ----------
        focus_chart_path = "focus_chart.png"
        fig_focus, ax2 = plt.subplots(figsize=(6, 3))
        ax2.plot(df["timestamp"], df["focus_score"], color="#00FF99")
        ax2.set_title("Focus Score Trend")
        fig_focus.savefig(focus_chart_path, dpi=200, bbox_inches="tight")
        plt.close(fig_focus)

        # ---------- DRAW INTO PDF ----------
        c.drawImage(status_chart_path, 50, 430, width=500, height=250)
        c.drawImage(focus_chart_path, 50, 150, width=500, height=250)

        c.save()

        # ---------- BACKEND UPLOAD ----------
        uploaded = upload_pdf_to_backend(
            pdf_path,
            title=f"Study Report - {selected_date}"
        )

        if uploaded:
            st.success("✅ PDF saved & visible in Analytics")
        else:
            st.warning("⚠️ PDF created but backend upload failed")

        with open(pdf_path, "rb") as f:
            st.download_button(
                "⬇️ Download Today",
                f,
                file_name="Today_Study_Report.pdf",
                mime="application/pdf"
            )

# ---------- TAB 5 (MERGED COMPARISON) ----------
with tabs[4]:

    st.subheader("📆 Weekly Comparison (This Week vs Last Week)")

    df_all = []
    for file in glob.glob(os.path.join(LOG_DIR, "*.csv")):
        date_str = os.path.basename(file).replace(".csv", "")
        try:
            d = pd.to_datetime(date_str)
        except:
            continue
        
        dfh = pd.read_csv(file)
        total = len(dfh)
        focused = dfh["status"].str.startswith("Focused").sum()
        pct = (focused / total * 100) if total else 0

        df_all.append([d, pct])

    if df_all:
        week_df = pd.DataFrame(df_all, columns=["Date", "Focus"])
        week_df["Week"] = week_df["Date"].dt.isocalendar().week

        latest_week = week_df["Week"].max()
        this_week = week_df[week_df["Week"] == latest_week]["Focus"].mean()

        if (latest_week - 1) in week_df["Week"].values:
            last_week = week_df[week_df["Week"] == (latest_week - 1)]["Focus"].mean()
        else:
            last_week = None

        st.write(f"🔥 **This Week Avg Focus:** {this_week:.1f}%")

        if last_week is not None:
            st.write(f"🕓 **Last Week Avg Focus:** {last_week:.1f}%")
            change = this_week - last_week

            if change > 0:
                st.success(f"✅ Improvement of **+{change:.1f}%** this week!")
            else:
                st.warning(f"⚠️ Decrease of **{-change:.1f}%** this week.")
        else:
            st.info("Not enough data to compare last week.")

    else:
        st.info("Not enough data recorded for weekly comparison.")


    st.markdown("---")
    st.subheader("🔄 Compare Two Days")
    d1 = st.selectbox("Select First Day", dates)
    d2 = st.selectbox("Select Second Day", dates)
    df1=pd.read_csv(os.path.join(LOG_DIR,d1+".csv"))
    df2=pd.read_csv(os.path.join(LOG_DIR,d2+".csv"))
    f1=(df1["status"].str.startswith("Focused").sum()/len(df1)*100)
    f2=(df2["status"].str.startswith("Focused").sum()/len(df2)*100)
    c1,c2=st.columns(2)
    c1.metric(d1,f"{f1:.1f}%"); c2.metric(d2,f"{f2:.1f}%")

# -------------------------
# 7) History Trend (line)
# -------------------------
with tabs[5]:
    st.subheader("📊 Focus Percentage Trend (History)")
    history = []
    for file in glob.glob(os.path.join(LOG_DIR, "*.csv")):
        dfh = pd.read_csv(file)
        date_str = os.path.basename(file).replace(".csv", "")
        total = len(dfh)
        focused = dfh["status"].str.startswith("Focused").sum()
        focus_pct_h = (focused / total * 100) if total else 0
        history.append([date_str, focus_pct_h])

    if history:
        history_df = pd.DataFrame(history, columns=["Date", "Focus %"]).sort_values("Date")
        fig3, ax = plt.subplots(figsize=(10, 4))
        ax.set_facecolor("#111111")
        fig3.patch.set_facecolor("#111111")
        ax.plot(history_df["Date"], history_df["Focus %"], marker="o", linewidth=2, color="#00FFAA")
        ax.set_xlabel("Date", color="white")
        ax.set_ylabel("Focus %", color="white")
        ax.set_title("Focus Improvement Over Days", color="white")
        ax.tick_params(axis="x", colors="white", rotation=45)
        ax.tick_params(axis="y", colors="white")
        st.pyplot(fig3)
        st.dataframe(history_df, use_container_width=True)
    else:
        st.info("No history found.")

# -------------------------
# 8) Raw Log
# -------------------------
with tabs[6]:
    st.subheader("🗂️ Raw Log Data")
    st.dataframe(df, use_container_width=True)